### ISSUE TITLE
[async_hooks] stable API - tracking issue

### ISSUE THREAD

**Issue by AndreasMadsen** [nodejs/diagnostics#124]
I posted requirements list for getting `async_hooks` into stable a while ago (https://github.com/nodejs/node/issues/14717#issuecomment-329755307). This is a very similar list.

### Internal Technical

- [ ] Clarify breaking changes necessary for better performance (issue: https://github.com/nodejs/benchmarking/issues/181)
  - [x] Remove `promise` object from `PromiseWrap` (PR: https://github.com/nodejs/node/pull/23443)
  - [ ] Use a "`MicrotaskWrap`" instead of `PromiseWrap` (issue: https://github.com/nodejs/diagnostics/issues/389)
- [ ] Setting up the benchmark suite to be run with and without `async_hooks` and see that there is only a small measurable difference given our tolerance. 
- [x] Deprecate `runInAsyncIdScope` (issue: https://github.com/nodejs/node/issues/14328, PR: https://github.com/nodejs/node/pull/16972)
- [x] Deprecate `setTriggerId` (issue: https://github.com/nodejs/node/issues/14238, PR: https://github.com/nodejs/node/pull/16972)
  - [x] Implement internal replacement that we can optionally expose (PR: https://github.com/nodejs/node/pull/17273)
- [x] Deprecate Sensitive Embedder API (issue: https://github.com/nodejs/node/issues/15572, PR: https://github.com/nodejs/node/pull/16972)
- [x] Separate internal API from the external API (PR: https://github.com/nodejs/node/pull/16972).
- [x] Remove deprecated API (PR: https://github.com/nodejs/node/pull/17147).
- [x] Opt-out `async_hooks` state validation in v9.x. (PR: https://github.com/nodejs/node/pull/16318)
- [ ] Make sure all nodecore uses of `MakeCallback` have an `async_context`.
- [x] Integrate `async_hooks` into `NAN` (issue: https://github.com/nodejs/node/issues/13254).
- [x] Integrate `async_hooks` into `n-api` (issue: https://github.com/nodejs/node/issues/13254).
### Internal Non-Technical

- [ ] Specify whether a `triggerAsyncId` change will be a `semver-major`, `semver-minor` or `semver-patch`.
- [ ] Identify "tolerance level" of perf impact of async-hooks, especailly regarding promises.
- [ ] Is Async Hooks exposing the right logical model? (issue: https://github.com/nodejs/diagnostics/issues/143)

### External Non-Technical

- [X] major APM vendor that uses `async_hooks` (N/Solid, [New Relic](https://blog.newrelic.com/2017/11/08/node-8-async-await-support/), [Elastic APM](https://github.com/elastic/apm-agent-nodejs/blob/master/lib/instrumentation/async-hooks.js))
- [X] npm modules with at least 5000 DL/month based on `async_hooks` (https://www.npmjs.com/package/trace & https://www.npmjs.com/package/cls-hooked)

### After Stable

- [x] Deprecate `MakeCallback` without `async_context` (PR: https://github.com/nodejs/node/pull/18632)

**Comment by refack** [comment]
@AndreasMadsen how about adding some external criteria, like TC39 uses or N-API (https://github.com/nodejs/node/issues/14532)
- [X] 1 major APM vendor that uses `async_hooks` (N/Solid)
- [X] 2 npm modules with at least 5000 DL/month based on `async_hooks` (https://www.npmjs.com/package/trace & https://www.npmjs.com/package/cls-hooked)

**Comment by AndreasMadsen** [comment]
@refack added your 1. and 2. to the list. I'm not sure what you mean by TC39 uses. Regarding N-API I don't see why that should be a requirement. `async_hooks` has its own native Embedder API outside N-API, we can mark that as stable without N-API. In fact N-API shouldn't be marked stable before the `async_hooks` native Embedder API is marked stable since they depend on that. But `async_hooks` doesn't depend on N-API.

**Comment by refack** [comment]
Thanks. I just referenced TC39 and N-API as processes that use exit criteria that are independent of the development process, but take into account ecosystem adoption. So I agree that stability of N-API and async_hooks are independent (except for the embedder API)

**Comment by vdeturckheim** [comment]
FWIW, We plan to start using Async Hooks in [Sqreen Agent](https://www.npmjs.com/package/sqreen) in the upcomming weeks.

**Comment by jkrems** [comment]
Link by @watson for elastic: https://github.com/elastic/apm-agent-nodejs/pull/77

**Comment by kjin** [comment]
PR to add async_hooks in Stackdriver Trace: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/538

**Comment by AndreasMadsen** [comment]
Updated "Deprecate setTriggerId"

**Comment by AndreasMadsen** [comment]
Added:

- Clarify breaking changes necessary for better performance (issue: https://github.com/nodejs/benchmarking/issues/181)

**Comment by bmeurer** [comment]
So based on discussion in the benchmarking WG meeting yesterday I did setup [test cases](https://github.com/bmeurer/async-hooks-performance-impact) to run the Promise heavy Bluebird and Wikipedia benchmarks (used by the V8 project) with and without `async_hooks` to answer the first question in this thread, and slow-down is pretty significant even with just an empty `init` hook.

@mhdawson suggested to kick-off some discussion on the performance via https://github.com/nodejs/benchmarking/issues/188 and bubble up the issue to make sure we consider the performance aspect before `async_hooks` goes out of *EXPERIMENTAL*.

**Comment by mike-kaufman** [comment]
FYI I added an item to list above to identify the perf impact we're willing to tolerate from async-hooks.  Current benchmark data cited in https://github.com/nodejs/benchmarking/issues/181 show a ~2x-3x slowdown.

**Comment by lykkin** [comment]
We haven't run into any blockers in the New Relic agent.

The primary concern we've come up against is an extension of the lifetime of a promise leads to drastically increased memory usage.  This only seems to be an issue with immediately resolved promises (e.g. `Promise.resolve()`), since those don't emit an  `after` event and have to be cleared on `destroy`.  This situation only causes an issue when there is an existing promise leak and just requires us to be more diligent about finding and eliminating leaks in libraries we interact with.  I don't think this issue affects the shape of the API, so it's definitely not a blocker.

We currently only instrument core promises using async hooks, though the data exposed through the hooks should be enough to move over the rest of the core instrumentation when the feature is fully released.

**Comment by ofrobots** [comment]
@lykkin do you have any data on real-world performance impact async-hooks adds to applications? Performance seems to be the main blocker at this point, and it would be good to learn what kind of impact you observe.

**Comment by mhdawson** [comment]
@ofrobots are you still able to champion this.

**Comment by ofrobots** [comment]
Unfortunately no. It would be great if someone else has the drive to drive async_hooks forward.

**Comment by gireeshpunathil** [comment]
should this remain open? [ I am trying to chase dormant issues to closure ]

**Comment by mariodu** [comment]
no one working on this?

**Comment by rochdev** [comment]
Since `async_hooks` is still unstable, I would keep this open until it's considered stable.

**Comment by xadamy** [comment]
Hey there! 👋 I work for AppSignal and we're currently working on a Node.js integration. While I haven't used it in our integration just yet, `async_hooks` is something I personally would like to see move forward. How can we best help with the effort to progress this?

**Comment by gireeshpunathil** [comment]
@xadamy - thanks. one thing I would suggest is join our bi-weekly diagnostic working group meeting,  and do a briefing on goal, engagement model, your availability etc. We will have one next to next Wednesday. makes sense?

**Comment by xadamy** [comment]
@gireeshpunathil Sounds good, I'll make sure I'm there next Wednesday! Thank you!

**Comment by xadamy** [comment]
@gireeshpunathil Apologies, did you mean today or next Wednesday for this?

**Comment by robin-rpr** [comment]
Hey @xadamy, sorry for jumping in here, the next Diagnostics WG Meeting is currently planned on Wednesday, 20. Nov 19:30 - 20:30 :)

**Comment by kamalmarhubi** [comment]
I figure this shouldn't go stale since it's a long-lived tracking issue?

**Comment by xadamy** [comment]
Hey team, sorry it has taken me so long to follow up. Last time we spoke I believe you asked me to experiment with the `async_hooks` API more. We now have an `async_hooks` implementation in production in [our Node.js integration](https://github.com/appsignal/appsignal-nodejs/blob/main/packages/nodejs/src/scope.ts) - although it is not much different (if at all) from Cloud Trace's implementation. 

I have some thoughts and feedback on the API that it would be great to sync with you all on at some point (if you have time), but it would be good to know if there's anything further you'd like me to do to move this forward?

**Comment by mhdawson** [comment]
@xadamy maybe you can plan to come ot the next diagnostics meeting and give the team a runthrough of your thoughts.

**Comment by mhdawson** [comment]
closing in favor of https://github.com/nodejs/diagnostics/issues/437
