### ISSUE TITLE
Diagnostics Summit - Recap and Actions

### ISSUE THREAD

**Issue by mhdawson** [nodejs/diagnostics#162]
The diagnostic summit was held this week (see https://github.com/nodejs/diagnostics/issues/121 for context).

This issue is to track pulling together the recap/actions that we need to track out of the discussions. We tagged the following people to do an initial summary as follows:

* [ ] Platform Neutrality/N-API discussion - @aruneshchandra
* [ ] Use cases and tools - @mhdawson, @mcollina 
* [x] Profiling - @mmarchini (context: https://github.com/nodejs/diagnostics/issues/148; Summit recap & actions: https://github.com/nodejs/diagnostics/issues/148#issuecomment-369348961)
* [ ] Async Context Formalization - @mike-kaufman 
* [x] Async Hooks (captured in existing issue #124, no action)
* [x] Debugging Time-travel - @mrkmarron (#164)
* [ ] Trace Events - @jasnell 
* [ ] Unhandled Rejection/Errors @Fishrock123 
* [ ] Intro's @mhdawson 
* [ ] Tools and Support expectations (@joyeecheung)
* [ ] CI testing (follow on deep dive meeting, issue created)

I suggest that each of us creates an issue with the summary and then I can try to pull them together into an overall recap.

**Comment by mhdawson** [comment]
Attaching my screen captures to use when putting together the overviews of next steps, actions and owners.

![p_20180212_110504_vhdr_on](https://user-images.githubusercontent.com/9373002/36228232-bbcbabee-11a1-11e8-8f36-ce55e518cc4e.jpg)
![p_20180212_113742_vhdr_on](https://user-images.githubusercontent.com/9373002/36228233-bbe8c224-11a1-11e8-9c70-7a49d3366db4.jpg)
![Uploading P_20180212_121140_vHDR_On.jpg…]()
![Uploading P_20180212_134720_vHDR_On.jpg…]()
![Uploading P_20180213_092552_vHDR_On.jpg…]()
![Uploading P_20180213_101437_vHDR_On.jpg…]()
![Uploading P_20180213_103530_vHDR_On.jpg…]()
![Uploading P_20180213_110452_vHDR_On.jpg…]()
![Uploading P_20180213_115112_vHDR_On.jpg…]()
![Uploading P_20180213_121221_vHDR_On.jpg…]()
![Uploading P_20180213_123126_vHDR_On.jpg…]()
![Uploading P_20180213_151722_vHDR_On.jpg…]()
![Uploading P_20180213_152340_vHDR_On.jpg…]()
![Uploading P_20180213_161831_vHDR_On.jpg…]()
![Uploading P_20180213_165853_vHDR_On.jpg…]()

**Comment by Fishrock123** [comment]
Heads up, I've converted the list in the issue decsription into a checklist.

**Comment by gireeshpunathil** [comment]
closing as completed
