### ISSUE TITLE
[async_hooks] tracking issue

### ISSUE THREAD

**Issue by AndreasMadsen** [nodejs/diagnostics#29]
**Missing Handle context**
- [x] TCPwrap created from server (issue: https://github.com/nodejs/node/issues/2986, PR: https://github.com/nodejs/node/pull/3216)
- [x] HTTP sockets `parserOnBody`
  - issues: https://github.com/nodejs/node/issues/3241, https://github.com/nodejs/node/issues/4416
  - PR: https://github.com/nodejs/node/pull/5419 and https://github.com/nodejs/node/pull/5591, ~~depends on: https://github.com/nodejs/node/pull/4507~~
- [x] Promises or Microtask in general 
  - ~~node issue: https://github.com/nodejs/promises/issues/9~~
  - ~~v8 issue: https://bugs.chromium.org/p/v8/issues/detail?id=4643~~
  - PR: nodejs/node#13000
  - additional PRs: https://github.com/nodejs/node/pull/13242, https://github.com/nodejs/node/pull/13224
- [x] nextTick (old issue: https://github.com/nodejs/node/issues/666, PR: https://github.com/nodejs/node/pull/12892)
- [x] setTimeout, setInterval, setImmediate
  - old issue: https://github.com/nodejs/node/issues/666, https://github.com/nodejs/node/pull/12892
  - PR: nodejs/node#12892
- [ ] `exit` and `beforeExit` has no context
  - ref: https://github.com/nodejs/node/pull/13142#pullrequestreview-40577964
  - issue: none
  - PR: none
- [x] `emitDestroy` doesn't emit `destroy` upon process termination (issue: https://github.com/nodejs/node/issues/13262, PR: https://github.com/nodejs/node/pull/13286)
- [x] addon modules integration with AsyncWrap (EP: https://github.com/nodejs/node-eps/pull/18, PR: https://github.com/nodejs/node/pull/13142)
- [ ] N-API addon modules integration with AsyncWrap (issue: https://github.com/nodejs/node/issues/13254, PR: none)
- [ ] NAN-API addon modules integration with AsyncWrap (issue: https://github.com/nodejs/node/issues/13254, PR: none)

**More events**
- [x] ~~onready (issue: https://github.com/nodejs/tracing-wg/issues/11) - unlikely to be solved~~. As of now, not part of `async_hooks` API.
  - Some debate regarding promises: https://github.com/nodejs/node/pull/13000#discussion_r116296676
- [x] ~~onerror (issue: https://github.com/nodejs/node/issues/669, https://github.com/nodejs/tracing-wg/issues/7) - awaiting use cases~~. As of now, not part of `async_hooks` API.
- [x] ondestructor (PR: https://github.com/nodejs/node/pull/3461)

**API**
- [x] `process.binding` is being deprecated by https://github.com/nodejs/node/pull/2768 (issue: missing, PR: https://github.com/nodejs/node/pull/12892)
- [x] support multiple independent `setupHooks` calls. (issue: https://github.com/nodejs/tracing-wg/issues/40, PR: https://github.com/nodejs/node/pull/12892)
- [x] async wrap hook error handling (PR: https://github.com/nodejs/node/pull/5756)
- [x] add exception throw flag to post hook (PR: https://github.com/nodejs/node/pull/5756)
- [x] add parent handle to init callback (PR: https://github.com/nodejs/node/pull/3216)
- [x] add unique id (PR: https://github.com/nodejs/node/pull/3461)
- [x] add unique id to all hooks: (PR: https://github.com/nodejs/node/pull/4600)
- [x] unique ids should be a double, int32 is not enough. (PR: https://github.com/nodejs/node/pull/7096)

**Documentation**
- [x] intial documentation (PR: https://github.com/nodejs/tracing-wg/pull/27)
- [x] document unique id (PR: https://github.com/nodejs/tracing-wg/pull/37)
- [x] document ondestructor (PR: https://github.com/nodejs/tracing-wg/pull/37)
- [x] document unique id on all hooks (PR: https://github.com/nodejs/tracing-wg/pull/39)
- [x] document public JS `async_hooks` API. (PR: https://github.com/nodejs/node/pull/13287) 
- [ ] document public C++ Embedder API – is the header file sufficient? (PR: none) 

---

If something is missing just edit this. But add a comment so we can keep the history.

**Comment by Qard** [comment]
Nice, thanks for putting this together! :smile_cat:

**Comment by AndreasMadsen** [comment]
Added:

- no proper way for native modules to integrate with AsyncWrap (PR: nodejs/node#3504)
- add unique id (PR: nodejs/node#3461)

**Comment by AndreasMadsen** [comment]
@trevnorris could you add a link to the Promises issue in v8.

**Comment by trevnorris** [comment]
@AndreasMadsen Sorry. Forgot about this. Here's the link: https://bugs.chromium.org/p/v8/issues/detail?id=4643

**Comment by chrisdickinson** [comment]
Adding https://github.com/nodejs/node/issues/4416 here.

**Comment by AndreasMadsen** [comment]
updates:

work is being done on:
- HTTP sockets `parserOnBody` (PR: https://github.com/nodejs/node/pull/4509, depends on: https://github.com/nodejs/node/pull/4507)

new:
- add unique id to all hooks: (PR: nodejs/node#4600)

**Comment by trevnorris** [comment]
Note: Getting MakeCallback reentrant, which is necessary to fix some issue with AsyncWrap, has been a bit of a pain. Hopefully will be able to finish it this week.

**Comment by trevnorris** [comment]
MakeCallback is now reentrant, and working on a few other improvements for an EnterpriseJS talk today. I'll throw them up in a PR later this week.

**Comment by AndreasMadsen** [comment]
Updated with PR: https://github.com/nodejs/node/pull/8531 and EP: https://github.com/nodejs/node-eps/pull/18

The current status is that **Promises** and **addon integration** is still a todo. The _Addon integration_ solution is documented in https://github.com/nodejs/node-eps/pull/18, but not yet implemented.

**Comment by Jeff-Lewis** [comment]
"[V8 promise hooks should ship with V8 5.7 and should be available in Node 8.](https://github.com/othiym23/node-continuation-local-storage/issues/98#issuecomment-275555070)" - ofrobots

**Comment by joshgav** [comment]
@trevnorris can you share an update?

**Comment by bajtos** [comment]
IMHO, it would be great if `async_hooks` were calling `V8Inspector::asyncTask*` to notify the built-in inspector (debugger) about async boundaries, allow the inspector to show long (async) stack traces in the UI. See https://github.com/nodejs/node/issues/11370

**Comment by AndreasMadsen** [comment]
`async_hooks` have landed as an undocumented API. Documentation will be added soon, see: https://github.com/nodejs/node/pull/12953

I have updated the tracking issue to reflect this.

**Comment by overlookmotel** [comment]
Great news! But does the fact that Promises/Microtask is not ticked off on OP indicate this isn't working yet?

**Comment by AndreasMadsen** [comment]
@overlookmotel Yes, Promises will come in another PR soon. It was excluded from nodejs/node#12953 because it was quite big and we wanted to land it before we got more merge conflicts.

**Comment by mhdawson** [comment]
Added this 
```
n-API addon modules integration with AsyncWrap (EP: nodejs/node-eps#18, PR: someone needs to be assigned).
```
as we need to cover both NaN and N-API

**Comment by matthewloring** [comment]
@overlookmotel Check out nodejs/node#13000

**Comment by AndreasMadsen** [comment]
The C++ Embedder API is in progress, added a PR reference: https://github.com/nodejs/node/pull/13142

**Comment by AndreasMadsen** [comment]
updated promise support status and added: "`exit` and `beforeExit` has no context" which we will likely address post node v.8.x

**Comment by AndreasMadsen** [comment]
C++ Embedder API has been implemented and merged. I've created an issue for integrating it with NAN and N-API.

**Comment by AndreasMadsen** [comment]
Closing this issue. I will create a new one for how we are going to bring `async_hooks` into stable.
