### ISSUE TITLE
User Journey tracking documentation

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/diagnostics#502]
This issue aims to track the remaining tutorials under [documentation](https://github.com/nodejs/diagnostics/tree/main/documentation) folder.

The https://github.com/nodejs/diagnostics/issues/439 contains the documents created in the WG Deep Dive and we are working to transpose them into live documents.

- [ ] Abnormal Termination
  - [X] Using exit stack traces
  - [X] Using diagnotics report
  - [ ] Using lldb
  - [X] Using valgrind
- [ ] CPU
- [ ] Crash
  - [ ] Using node report
  - [ ] Using llnode
- [ ] Hang
  - [X] Using trace sigint
  - [X] Using Chrome DevTools
  - [ ] Using node report
- [ ] Live Debugging
  - [ ] Using Node Inspector
- [ ] Memory
  - [ ] Using Heap Profiler
  - [X] Using Heap Snapshot
  - [X] Using GC Traces
  - [X] Using Native Tools
- [ ] Profiling
  - [X] Using V8 Profiler
  - [X] Using Linux Perf
  - [ ] Using Native Tools
- [ ] Tracing
  - [ ] Using Trace Events

Feel free to update this description when a tutorial is done.

cc: @nodejs/diagnostics

**Comment by RafaelGSS** [comment]
What we are supposed to do in _CPU_ journey? It looks pretty similar to what we did in _Profiling_.

**Comment by mhdawson** [comment]
@RafaelGSS a few thoughts:

1) The goal was to be based on a user journey (ie problem->resolution) versus tool based. In that context we should probably rename "Profiling" to "Poor Performance".
2) CPU should then likely be "Excessive CPU usage". The symptoms would be different (ie performance could be fine, but you may be using more CPU than expected/wanted).  The Debugging might then be the same as figuring out where CPU is used will be the same between the 2.

**Comment by RafaelGSS** [comment]
I'm adding it to the agenda to discuss how we can expose it to the community in a call for help. Maybe a tweet could be enough?

**Comment by tony-go** [comment]
Hey @mhdawson @RafaelGSS 👋 

A question regarding "Monitoring Excessive CPU Usage" we want to help Node.Js users to have a real-time CPU monitoring solution or an on-demand tool that is runnable locally?

**Comment by RafaelGSS** [comment]
> Hey @mhdawson @RafaelGSS wave
> 
> A question regarding "Monitoring Excessive CPU Usage" we want to help Node.Js users to have a real-time CPU monitoring solution or an on-demand tool that is runnable locally?

The idea is to show a few ways to monitor excessive CPU usage. Each step can be either an open-source tool or a built-in one.

**Comment by tony-go** [comment]
> @nodejs/diagnostics The memory set of documents is done, so I think we can move it to nodejs.org. The remaining question is: Where it should be placed?
> 
> cc: @nodejs/website

Once we merge it to the nodejs.org website, should we delete it from here and put a link to the nodejs.org repo?

**Comment by RafaelGSS** [comment]
> > @nodejs/diagnostics The memory set of documents is done, so I think we can move it to nodejs.org. The remaining question is: Where it should be placed?
> > cc: @nodejs/website
> 
> Once we merge it to the nodejs.org website, should we delete it from here and put a link to the nodejs.org repo?

I think we can point to the nodejs.org repo, but the exercises like #572 should remain here.

**Comment by RafaelGSS** [comment]
@No9 We have a mention to `lldb` when diagnosing of _Abnormal Termination_, but given the fact that `llnode` is an lldb plugin and most of its content will be covered in `Using llnode`, sounds reasonable to remove `Using lldb` from the list, what do you think?

**Comment by RafaelGSS** [comment]
@nodejs/website is that possible to get some insights from the guides we are creating? I'm not sure if that's getting traction. In case not, I'd suggest to the team to close this issue even without completing the list.

By insights I mean, visualizations per day in comparison to other pages

**Comment by Trott** [comment]
> @nodejs/website is that possible to get some insights from the guides we are creating? I'm not sure if that's getting traction. In case not, I'd suggest to the team to close this issue even without completing the list.
> 
> By insights I mean, visualizations per day in comparison to other pages

We removed Google Analytics/tracking some years ago. (I'd be fine with putting it back, but I'm also fine deferring to the people who really want to err on the side of privacy in these things.) We do have some log files that can be crunched to get usage, but I believe that would involve people from @nodejs/build.

**Comment by RafaelGSS** [comment]
Don't we use Cloudflare? IIRC we can get the same insights from their dashboards.

**Comment by richardlau** [comment]
We do use CloudFlare but access to that is restricted to the build-infra team.

The CloudFlare data is where the numbers for https://nodejs.org/metrics/ (leading to https://storage.googleapis.com/access-logs-summaries-nodejs/index.html) come from. Those only contain numbers for the downloads -- code in https://github.com/nodejs/build/tree/main/ansible/roles/metrics filters for the download files and strips out identifying information before publishing to the Google storage bucket.

**Comment by RafaelGSS** [comment]
Happy to add it to the agenda if someone else wants to pursue this work.
