### ISSUE TITLE
[trace] tracking issue; out of experimental

### ISSUE THREAD

**Issue by joshgav** [nodejs/diagnostics#84]
This issue is to track ongoing work to refine Trace Events in Node and graduate it from experimental state. 

It builds on and replaces

* https://github.com/nodejs/diagnostics/issues/30
* https://github.com/nodejs/diagnostics/issues/53

Initial Trace PR including discussion: [node#9304](https://github.com/nodejs/node/pull/9304)

todo:

- [ ] configurable output destinations
- [ ] add a listener system (#81)
- [ ] C/C++ API (#83)
- [ ] JavaScript API ([node-eps#48](https://github.com/nodejs/node-eps/pull/48))
- [ ] add trace points to nodejs/node (#82)
- [ ] relationship to upstream `trace_event_common.h` (see https://github.com/nodejs/node/pull/10628)
- [ ] recommendations for naming categories for ecosystem

**Comment by gireeshpunathil** [comment]
should this remain open? [ I am trying to chase dormant issues to closure ]

**Comment by jasnell** [comment]
Yes, this is not yet completed

**Comment by mmarchini** [comment]
Keeping this open, but we need to triage the todo list to identify which items were completed, which items are not relevant anymore, and any missing items.
